name: ahorra_gas
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.8
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  http: ^1.3.0
  lottie: ^3.3.1
  mockito: ^5.4.6
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/
    - lib/assets/icons/
    - lib/assets/gaslogo/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/img/logo.png"  # Ruta de la imagen para el ícono


